# Generated by Django 2.1.2 on 2019-05-24 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('twieetid', models.CharField(max_length=50)),
                ('screen_name', models.CharField(max_length=100)),
                ('media_id_str', models.CharField(max_length=50)),
                ('media_url_https', models.URLField()),
                ('text', models.TextField(blank=True)),
                ('hashtags_text', models.CharField(blank=True, max_length=50)),
                ('retweet_count', models.IntegerField()),
                ('favorite_count', models.IntegerField()),
                ('has_multiple_media', models.BooleanField()),
                ('label', models.IntegerField(null=True)),
                ('subdata1', models.TextField(null=True)),
                ('subdata2', models.TextField(null=True)),
                ('subdata3', models.IntegerField(null=True)),
                ('labeler', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
