# Generated by Django 2.1.2 on 2019-05-25 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getImagesFromTwitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='twieetid',
            new_name='id_str',
        ),
    ]
