# Generated by Django 2.1.2 on 2019-05-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getImagesFromTwitter', '0003_auto_20190530_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='hashtags_text',
            field=models.TextField(blank=True),
        ),
    ]
