# Generated by Django 2.1.2 on 2019-05-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getImagesFromTwitter', '0004_auto_20190530_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='text',
            field=models.BinaryField(blank=True),
        ),
    ]
